spring:
  application:
    name: ${project.name}
    version: ${project.version}
    description: ${project.description}

  datasource:
    url: jdbc:postgresql://localhost:5433/inventaries_db  # Cambiado a puerto 5433
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 9099

springdoc:
  api-docs:
    path: /api-docs # JSON
  swagger-ui:
    path: /swagger-ui.html # UI visual
    operations-sorter: method
    tags-sorter: alpha
    filter: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    org.flywaydb: DEBUG
    com.linktic.challenge.products: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  compression:
    request:
      enabled: true
    response:
      enabled: true

app:
  services:
    product-service:
      url: http://localhost:9091